### ISSUE TITLE
[borja.dolagaray][w5-project_visualizacion]

### ISSUE THREAD

**Issue by borjadola** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#1]
https://github.com/borjadola/Proyecto_visual_precipitaciones.git

**Comment by OrianAmpuero** [comment]
Bien Borja, el repo organizado y el readme sencillo pero no está mal aunque yo le pusiera alguna captura del powerbi o algo más visual para que se note de que va el proyecto y capte la atención; pendiente porque el link del heatmap no funciona. Y en cuanto a la powerbi, poco visual los datos, tienes problemas con el mapa ya que salta error, las páginas no tienen nombre pero tampoco los reportes tienes título, sé que puedes mejorar esta área pero se necesita tiempo y quizás me sorprendas en el proyecto final...
