### ISSUE TITLE
[Rodrigo](Visualization)

### ISSUE THREAD

**Issue by rodrigogtz99** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#11]
https://github.com/rodrigogtz99/w5-project_visualizacion.git

**Comment by OrianAmpuero** [comment]
Bien Rodrigo! Al repo le falta organización y el readme esta bien con comentarios que ayudan a entender mejor los datos, trata de poner el link mas accesible (en un hipervínculo, o directamente en el readme...). En cuanto a la visualización las páginas deberían de tener un título para introducir más allá de solo poner un número, además hay páginas con gráficos que muestran la misma info y no hace falta, la idea de que haya mas de un gráfico en la misma hoja es que sean interactivos y es lo que agrada de un dashboard, ahí te faltó relacionar o lograr esa unión.
