### ISSUE TITLE
[MartaRG] (Netflix_stats)

### ISSUE THREAD

**Issue by MartaRggc** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#12]
Perdón, que se me olvidó hacer la issue.

https://github.com/MartaRggc/Netflix_stats

**Comment by OrianAmpuero** [comment]
Buen trabajo Marta! El repo organizado y muy buen readme, pero no pude ver el powerbi así que no se si se te olvido pegar el link o el .pbix del archivo. Por lo que pude ver esta muy bien tanto la paleta de colores como los gráficos y la muestra de datos pero trata de insertar el powerbi para que realmente se pueda ver el trabajo realizado.

**Comment by MartaRggc** [comment]
Hola Oriana! Ya he subido el fichero de powerbi, que pensaba que con las
capturas bastaba.

Un saludo!
