### ISSUE TITLE
(IbaiGallego)[w5-project_visualization]

### ISSUE THREAD

**Issue by IbaiGallego** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#2]
https://github.com/IbaiGallego/Youtube_Visualization.git

**Comment by OrianAmpuero** [comment]
Buen trabajo Ibai! El repo y readme bien, en cuanto a la visualización en general esta bien aunque hubiese juntado varios gráficos para hacerlo interactivo, la idea de este proyecto era jugar un poco más con todas las posibilidades que te dan estas interfaces como powerbi o tableau, lograr mostrar de forma clara los datos sin mucha explicación pero obviamente lleva tiempo. Espero que hayas aprovechado esa semana y que te sirva para el proyecto final.
