### ISSUE TITLE
(NICO GCD)[w5-project_visualization]

### ISSUE THREAD

**Issue by NGCOS46** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#3]
https://github.com/NGCOS46/w5-data-visuals

**Comment by OrianAmpuero** [comment]
Bien Nico! El repo y readme correcto aunque yo le hubiese puesto algo más visual como capturas del powerbi.
En cuanto a la visualización me parece muy sencilla, sin una paleta de colores adecuada, los títulos de los gráficos suelen ayudar a guiar un poco con los datos pero no los editaste, en la última página tienes todos los filtros para una sola persona pero luego si seleccionas al otro se queda la mayoría en blanco y no se ve muy bien además que confunde un poco esa misma hoja.
Entiendo que es una interfaz con mucho que hacer para pocos días pero es cuestión de echarle horas para ir mejorando.
