### ISSUE TITLE
[Nico.V](Project Visualization)

### ISSUE THREAD

**Issue by nicovilla23** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#4]
https://github.com/nicovilla23/Project_visualization/tree/main

**Comment by OrianAmpuero** [comment]
Bien Nico! El repo y el readme bien desarrollado y organizado; en cuanto al Tableau, no hay nombre de páginas para uno tener una idea de que va cada cosa, hay gráficos encima de otros que dan la misma información y no tiene sentido, los gráficos no interactúan entre sí cuando hay más de uno y esa es un poco la idea de los dashboards.
