### ISSUE TITLE
[Esteban]w5-project_visualizacion

### ISSUE THREAD

**Issue by esteban-bit** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#5]
https://github.com/esteban-bit/project_visualizacion.git

**Comment by OrianAmpuero** [comment]
Bien Esteban! El repo bien organizado y buen readme pero pendiente de no escribir en dos idiomas. En cuanto al tableau no pude entrar, no hay ningún link así que solo me guio por las capturas que pusiste ahí pero es verdad que lo que veo esta bien y las conclusiones ayudan mucho a entender los datos.
