### ISSUE TITLE
[Carlos González](proyecto_visualización)

### ISSUE THREAD

**Issue by chiinwy** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#6]
https://github.com/chiinwy/Proyecto_Visualizacion

**Comment by OrianAmpuero** [comment]
Bien Carlos, el repo correcto y el readme esta mejorable; en cuanto al powerbi entiendo bien la primera página pero de resto no le veo mucho sentido y siento que no enriquecen mucho a la visualización. Espero que hayas aprovechado esa semana para conocer diferentes interfaces de visualización y te sirvan para el proyecto final.
