### ISSUE TITLE
[Lola] (w5-project_visualizacion)

### ISSUE THREAD

**Issue by delbrioariasl** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#7]
https://github.com/delbrioariasl/W5_Projecto_Visualizacion

**Comment by OrianAmpuero** [comment]
Buen trabajo Lola! El repo y readme bien, en cuanto a la visualización me parece correcta pero trata de que siempre el país tenga el mismo color para no confundir y en general me pareció sencilla pero creo que se le puede sacar mucho más a este tema dedicándole tiempo. Ya se verá si lo eliges como proyecto final.
