### ISSUE TITLE
[Jaime](w5-project_visualizacion )

### ISSUE THREAD

**Issue by RCJaime** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#8]
https://github.com/Jaimercmail/ETL-Visualizacion.git

**Comment by OrianAmpuero** [comment]
Buen trabajo Jaime!! El repo y readme bien pero cuidado de no mezclar idiomas, en cuanto al powerbi me gusto bastante, desde la paleta de colores como los gráficos elegidos para mostrar la info más clara, así que en general me parece que has logrado aprovechar la semana de visualización.
