### ISSUE TITLE
[David](w5-project_visualizacion )

### ISSUE THREAD

**Issue by DavidNPastrana** [Ironhack-Data-Madrid-Julio-2023/w5-project_visualizacion#9]

**Comment by DavidNPastrana** [comment]
https://github.com/DavidNPastrana/Data_visualization

**Comment by OrianAmpuero** [comment]
Buen trabajo David! El repo y readme bien, en cuanto a la visualización siento que le falta, es decir, afecta el hecho de tener pocos datos obviamente y eso se ve reflejado en el análisis; de resto creo que has sacado conclusiones que ayudan a entender los datos, trata de cuidar la paleta de colores para que tenga sentido con el tema y tratar de al tener más de un gráfico en una misma hoja puedan estar relacionados ya que la idea de un dashboard es que sean interactivos (que al hacer click en uno el otro también te de info).
